server:
  port: 8080
  servlet-path: /seckill
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seckill
  freemarker:
    check-template-location: false
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp



