spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&amp;useUnicode=true
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.mrpeng.entity
  mapper-locations: classpath:mapper/*.xml

